server:
  port: 6003

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#940527000

spring:
  application:
    name: appgateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: app_seguridad
        uri: http://localhost:8088
        predicates:
          - Path=/seguridad/**
        filters:
          - StripPrefix=1
      - id: app_factura
        uri: http://localhost:8086
        predicates:
          - Path=/factura/**
        filters:
          - StripPrefix=1
      - id: app_pago
        uri: http://localhost:8087
        predicates:
          - Path=/pago/**
        filters:
          - StripPrefix=1
      - id: app_movement
        uri: http://localhost:8085
        predicates:
          - Path=/movimiento/**
        filters:
          - StripPrefix=1
